//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorageEntities : DbContext
    {
        public StorageEntities()
            : base("name=StorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<IPs> IPs { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Reply> Reply { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<TopicReply> TopicReply { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserActor> UserActor { get; set; }
        public virtual DbSet<UserMovie> UserMovie { get; set; }
        public virtual DbSet<UserReply> UserReply { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserTopic> UserTopic { get; set; }
    }
}
