//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovie
    {
        public int UserMovie_ID { get; set; }
        public int User_ID { get; set; }
        public int Movie_ID { get; set; }
        public System.DateTime Review_Date { get; set; }
        public string Review_Text { get; set; }
        public byte Review_Grade { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual User User { get; set; }
    }
}
